/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.teacher;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import view.main.FrmPrincipal;
import controller.data.ControllerTeacher;
/**
 *
 * @author tisan
 */
public class FrmProfesorPrincipal extends javax.swing.JInternalFrame {

  private ControllerTeacher controladorProfesor;
    private FrmPrincipal frmPrincipal;
    /**
     * Creates new form FrmProfesorPrincipal
     * @param frmPrincipal
     */
    public FrmProfesorPrincipal(FrmPrincipal frmPrincipal) {
        initComponents();
        this.frmPrincipal=frmPrincipal;
        controladorProfesor=new ControllerTeacher();
        controladorProfesor.cargarGrillaProfesor(tblProfesor, String.valueOf(cmbVistaProfesor.getSelectedItem()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbVistaProfesor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfesor = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();

        setTitle("ADMINISTRAR PROFESORES");
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(610, 250));
        setPreferredSize(new java.awt.Dimension(610, 250));
        getContentPane().setLayout(null);

        jLabel1.setText("Mostrar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 15, 70, 14);

        cmbVistaProfesor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));
        getContentPane().add(cmbVistaProfesor);
        cmbVistaProfesor.setBounds(80, 10, 190, 20);

        tblProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Netbook", "Apellido y Nombre", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProfesor);
        if (tblProfesor.getColumnModel().getColumnCount() > 0) {
            tblProfesor.getColumnModel().getColumn(0).setResizable(false);
            tblProfesor.getColumnModel().getColumn(1).setResizable(false);
            tblProfesor.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 452, 120);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/add204.png"))); // NOI18N
        btnAgregar.setToolTipText("Profesor Nuevo");
        btnAgregar.setMaximumSize(new java.awt.Dimension(40, 35));
        btnAgregar.setMinimumSize(new java.awt.Dimension(40, 35));
        btnAgregar.setPreferredSize(new java.awt.Dimension(40, 35));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(470, 50, 40, 35);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/logout13.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(40, 35));
        btnSalir.setMinimumSize(new java.awt.Dimension(40, 35));
        btnSalir.setPreferredSize(new java.awt.Dimension(40, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(550, 170, 40, 35);

        btnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/file-format.png"))); // NOI18N
        btnPdf.setToolTipText("Ver PFD");
        btnPdf.setMaximumSize(new java.awt.Dimension(120, 26));
        btnPdf.setMinimumSize(new java.awt.Dimension(120, 26));
        btnPdf.setPreferredSize(new java.awt.Dimension(40, 35));
        getContentPane().add(btnPdf);
        btnPdf.setBounds(470, 90, 40, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        FrmProfesorCRUD frmProfesorCRUD = new FrmProfesorCRUD(frmPrincipal, 'a');
        frmPrincipal.getDesktopPane().add(frmProfesorCRUD);
        frmProfesorCRUD.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int respuesta=JOptionPane.showConfirmDialog(this, "¿Desea Salir?","Salir",JOptionPane.YES_NO_OPTION);
        if(respuesta==JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbVistaProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProfesor;
    // End of variables declaration//GEN-END:variables
    public JTable getTblProfesores(){
        return tblProfesor;
    }
}
