/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.technicalService;

import view.main.FrmPrincipal;
import controller.data.ControladorServicioTecnico;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.domain.Netbook;
import model.domain.ServicioTecnico;

/**
 *
 * @author wally86
 */
public class FrmServicioTecnicoCRUD extends javax.swing.JInternalFrame {

    private FrmPrincipal frmPrincipal;
    private ControladorServicioTecnico controladorServicioTecnico;
    private char tipoTransaccion;
    private char tipoTitular;

    /**
     * Creates new form FrmServicioTecnicoPrincipal
     *
     * @param frmPrincipal
     */
    public FrmServicioTecnicoCRUD(FrmPrincipal frmPrincipal, char tipoTransaccion, char tipoTitualar) {
        initComponents();
        this.tipoTransaccion = tipoTransaccion;
        this.frmPrincipal = frmPrincipal;
        this.controladorServicioTecnico = new ControladorServicioTecnico();
        this.tipoTitular = tipoTitualar;
        cargarDatos();
    }

    private void cargarDatos() {

        switch (getTipoTransaccion()) {
            case 'a':

                controladorServicioTecnico.cargarDatosAlta(this, getTipoTitular());
                break;
            case 'v':
                break;
            case 'm':
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroserie = new javax.swing.JTextField();
        txtIdHardware = new javax.swing.JTextField();
        txtDniTitular = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFechaSolicitud = new javax.swing.JTextField();

        setTitle("SOLICITUD SERVICIO TÉCNICO");
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(380, 430));
        setPreferredSize(new java.awt.Dimension(380, 430));
        getContentPane().setLayout(null);

        txtNumeroserie.setEditable(false);
        getContentPane().add(txtNumeroserie);
        txtNumeroserie.setBounds(130, 15, 190, 20);

        txtIdHardware.setEditable(false);
        getContentPane().add(txtIdHardware);
        txtIdHardware.setBounds(130, 65, 190, 20);

        txtDniTitular.setEditable(false);
        getContentPane().add(txtDniTitular);
        txtDniTitular.setBounds(130, 115, 190, 20);

        txtDiagnostico.setColumns(15);
        txtDiagnostico.setRows(5);
        jScrollPane1.setViewportView(txtDiagnostico);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 230, 190, 100);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/imagen/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(120, 26));
        btnGuardar.setMinimumSize(new java.awt.Dimension(120, 26));
        btnGuardar.setPreferredSize(new java.awt.Dimension(120, 26));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(20, 350, 120, 26);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/imagen/no.png"))); // NOI18N
        btnSalir.setText("Cancelar");
        btnSalir.setMaximumSize(new java.awt.Dimension(120, 26));
        btnSalir.setMinimumSize(new java.awt.Dimension(120, 26));
        btnSalir.setPreferredSize(new java.awt.Dimension(120, 26));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(210, 350, 120, 26);

        jLabel1.setText("Nº de Serie");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 100, 14);

        jLabel2.setText("Id Hardware");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 100, 14);

        jLabel3.setText("Dni Titular");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 120, 14);

        jLabel4.setText("Diagnóstico");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 110, 30);

        jLabel5.setText("Fecha de Solicitud");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 120, 14);

        txtFechaSolicitud.setEditable(false);
        getContentPane().add(txtFechaSolicitud);
        txtFechaSolicitud.setBounds(130, 165, 190, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardar() {
        controladorServicioTecnico.guardarServicioTecnico(this);
        frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorFormularioUsuario().actualizarCantidadServicioTecnico(frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal));
        JOptionPane.showMessageDialog(this, "Se guerdo el Registro correctamente");
        dispose();
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        boolean existeEnServicioTecnico;
        boolean existeEnPase;
        boolean paseRealizado=false;
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Esta seguro de guardar el Registro?", "Guardar", JOptionPane.YES_NO_OPTION);
        Netbook netbook;
        if (respuesta == JOptionPane.YES_OPTION) {
            if (tipoTitular == 'a') {
                existeEnServicioTecnico = controladorServicioTecnico.verificarExistencia(frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook());
                existeEnPase = frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorPase().verificarExistencia(frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook());
                netbook = frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook();
                try{
                paseRealizado = frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorPase().obtenerPaseSegunNetbook(netbook).isEstado();
                }catch(NullPointerException ex){
                    //JOptionPane.showMessageDialog(this,"Error en la consulta a pase realizado"+ex);
                }
                } else {
                existeEnServicioTecnico = controladorServicioTecnico.verificarExistencia(frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorProfesor().getNetbook());
                existeEnPase = frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorPase().verificarExistencia(frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorProfesor().getNetbook());
                netbook = frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorProfesor().getNetbook();
                try{
                paseRealizado = frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorPase().obtenerPaseSegunNetbook(netbook).isEstado();
                }catch(NullPointerException ex){
                    //JOptionPane.showMessageDialog(this, "Error en la consulta a pase realizado"+ex);
                }
                }

            //verifica si esta en latabla de st
            if (!existeEnServicioTecnico) {
                //verifica que si existe en la tabla pase y si ya se haya efectuado
                if (!existeEnPase) {
                    guardar();
                } else {
                    if (!paseRealizado) {
                        guardar();
                    } else {
                        JOptionPane.showMessageDialog(this, "Debe efectuar el pase antes de solicitar Servicio Tecnico");
                    }
                }
            } else {
                ServicioTecnico servicioTecnico = controladorServicioTecnico.obtenerServicioTecnicoPorNetbook(netbook);
                if (servicioTecnico.isEstado()) {
                    guardar();
                } else {
                    JOptionPane.showMessageDialog(this, "La netbook ya se encuentra con un pedido de Servicio Tecnico");
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea Salir", "Salir", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtDniTitular;
    private javax.swing.JTextField txtFechaSolicitud;
    private javax.swing.JTextField txtIdHardware;
    private javax.swing.JTextField txtNumeroserie;
    // End of variables declaration//GEN-END:variables

    public FrmPrincipal getFrmPrincial() {
        return this.frmPrincipal;
    }

    public JTextArea getTxtArea() {
        return txtDiagnostico;
    }

    public JTextField getTxtNumeroSerie() {
        return txtNumeroserie;
    }

    public JTextField getTxtDniTitular() {
        return txtDniTitular;
    }

    public JTextField getTxtIdHardware() {
        return txtIdHardware;
    }

    public JTextField getTxtFechaSolicitud() {
        return txtFechaSolicitud;
    }

    /**
     * @return the tipoTransaccion
     */
    public char getTipoTransaccion() {
        return tipoTransaccion;
    }

    /**
     * @return the tipoTitular
     */
    public char getTipoTitular() {
        return tipoTitular;
    }
}
