package model.domain;
// Generated 14/08/2014 10:07:55 by Hibernate Tools 3.6.0

import hibernate.dao.PersonaDAO;





/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements Comparable<Alumno> {


     private int idAlumno;
     private Tutor tutor;
     private Netbook netbook;
     private Persona persona;
     private String curso;
     private String division;
     private String estado;
     private String foto;

    public Alumno() {
    }

	
   
    public Alumno(int idalumno, Tutor tutor, Netbook netbook, Persona persona, String curso, String division, String estado, String foto) {
       this.idAlumno = idalumno;
       this.tutor = tutor;
       this.netbook = netbook;
       this.persona = persona;
       this.curso = curso;
       this.division = division;
       this.estado = estado;
       this.foto = foto;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Tutor getTutor() {
        return this.tutor;
    }
    
    public void setTutor(Tutor tutor) {
        this.tutor = tutor;
    }
    public Netbook getNetbook() {
        return this.netbook;
    }
    
    public void setNetbook(Netbook netbook) {
        this.netbook = netbook;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    @Override
    public int compareTo(Alumno alumno) {
        PersonaDAO personaDAO = new PersonaDAO();
        Persona p1 = personaDAO.obtenerPersonaPorId(this.persona.getIdPersona());
        Persona p2 = personaDAO.obtenerPersonaPorId(alumno.persona.getIdPersona());
        return Integer.valueOf(p1.getDni()).compareTo(p2.getDni());
    }
    
    


}


