package model.domain;
// Generated 14/08/2014 10:07:55 by Hibernate Tools 3.6.0



/**
 * Establecimiento generated by hbm2java
 */
public class Establecimiento  implements java.io.Serializable {


     private short idEstablecimiento;
     private String nombre;
     private String localidad;
     

    public Establecimiento() {
    }

	
    public Establecimiento(short idEstablecimiento, String nombre, String localidad) {
        this.idEstablecimiento = idEstablecimiento;
        this.nombre = nombre;
        this.localidad = localidad;
    }
    
   
    public short getIdEstablecimiento() {
        return this.idEstablecimiento;
    }
    
    public void setIdEstablecimiento(short idEstablecimiento) {
        this.idEstablecimiento = idEstablecimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    




}


