package model.domain;
// Generated 14/08/2014 10:07:55 by Hibernate Tools 3.6.0



/**
 * Netbook generated by hbm2java
 */
public class Netbook  implements java.io.Serializable {


     private String idNetbook;
     private String marca;
     private boolean estado;
     private String windowsKey;
     private String officeKey;
     private String modelo;
     private String idHardware;
     private String codigoActivador;

    public Netbook() {
    }

	
    public Netbook(String idnetbook, String marca, boolean estado, String windowsKey, String officeKey, String modelo, String idHardware, String codigoActivador) {
        this.idNetbook = idnetbook;
        this.marca = marca;
        this.estado = estado;
        this.windowsKey = windowsKey;
        this.officeKey = officeKey;
        this.modelo = modelo;
        this.idHardware = idHardware;
        this.codigoActivador= codigoActivador;
    }
    
   
    public String getIdNetbook() {
        return this.idNetbook;
    }
    
    public void setIdNetbook(String idNetbook) {
        this.idNetbook = idNetbook;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getWindowsKey() {
        return this.windowsKey;
    }
    
    public void setWindowsKey(String windowsKey) {
        this.windowsKey = windowsKey;
    }
    public String getOfficeKey() {
        return this.officeKey;
    }
    
    public void setOfficeKey(String officeKey) {
        this.officeKey = officeKey;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getIdHardware() {
        return this.idHardware;
    }
    
    public void setIdHardware(String idHardware) {
        this.idHardware = idHardware;
    }

    /**
     * @return the codigoActivador
     */
    public String getCodigoActivador() {
        return codigoActivador;
    }

    /**
     * @param codigoActivador the codigoActivador to set
     */
    public void setCodigoActivador(String codigoActivador) {
        this.codigoActivador = codigoActivador;
    }
    




}


