package model.domain;
// Generated 14/08/2014 10:07:55 by Hibernate Tools 3.6.0






/**
 * Pase generated by hbm2java
 */
public class Pase  implements java.io.Serializable {


     private int idPase;
     private Netbook netbook;
     private boolean estado;
     private String sn;
     private String bitArranque;
     private String servidor;

    public Pase() {
    }

    public Pase(int idpase, Netbook netbook, boolean estado, String sn, String bitArranque, String servidor) {
       this.idPase = idpase;
       this.netbook = netbook;
       this.estado = estado;
       this.sn = sn;
       this.bitArranque = bitArranque;
       this.servidor = servidor;
    }
   
    public int getIdPase() {
        return this.idPase;
    }
    
    public void setIdPase(int idPase) {
        this.idPase = idPase;
    }
    public Netbook getNetbook() {
        return this.netbook;
    }
    
    public void setNetbook(Netbook netbook) {
        this.netbook = netbook;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getSn() {
        return this.sn;
    }
    
    public void setSn(String sn) {
        this.sn = sn;
    }
    public String getBitArranque() {
        return this.bitArranque;
    }
    
    public void setBitArranque(String bitArranque) {
        this.bitArranque = bitArranque;
    }
    public String getServidor() {
        return this.servidor;
    }
    
    public void setServidor(String servidor) {
        this.servidor = servidor;
    }




}


