package model.domain;
// Generated 14/08/2014 10:07:55 by Hibernate Tools 3.6.0

import java.util.Comparator;
import java.util.Collection;




/**
 * Persona generated by hbm2java
 */
public class Persona implements Comparable<Persona>{


     private int idPersona;
     private String nombre;
     private String apellido;
     private int dni;
     private boolean estado;
     
    public Persona() {
    }

	
    public Persona(int idpersona, String nombre, String apellido, int dni, boolean estado) {
        this.idPersona = idpersona;
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.estado = estado;
    }
    
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    
//    @Override
//    public int comparar(Object elementoComparado) {
//        
//        return Integer.valueOf(getDni()).compareTo(((Persona)elementoComparado).getDni());
//    }

    @Override
    public int compareTo(Persona o) {
       return Integer.valueOf(this.getDni()).compareTo(o.getDni());
    }
 
    



}


