package model.domain;
// Generated 14/08/2014 10:07:55 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ServicioTecnico generated by hbm2java
 */
public class ServicioTecnico  implements java.io.Serializable {


     private int idServicioTecnico;
     private Netbook netbook;
     private String diagnostico;
     private Date fechaEntrega;
     private Date fechaDevolucion;
     private boolean estado;
     private int idSolicitud;

    public ServicioTecnico() {
    }
    
    public ServicioTecnico(int idserviciotecnico, Netbook netbook, String diagnostico, Date fechaEntrega, Date fechaDevolucion, boolean estado, int idSolicitud) {
       this.idServicioTecnico = idserviciotecnico;
       this.netbook = netbook;
       this.diagnostico = diagnostico;
       this.fechaEntrega = fechaEntrega;
       this.fechaDevolucion = fechaDevolucion;
       this.estado = estado;
       this.idSolicitud=idSolicitud;
    }
   
    public int getIdServicioTecnico() {
        return this.idServicioTecnico;
    }
    
    public void setIdServicioTecnico(int idServicioTecnico) {
        this.idServicioTecnico = idServicioTecnico;
    }
    public Netbook getNetbook() {
        return this.netbook;
    }
    
    public void setNetbook(Netbook netbook) {
        this.netbook = netbook;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    /**
     * @return the idSolicitud
     */
    public int getIdSolicitud() {
        return idSolicitud;
    }

    /**
     * @param idSolicitud the idSolicitud to set
     */
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }




}


