package model.domain;
// Generated 14/08/2014 10:07:55 by Hibernate Tools 3.6.0



/**
 * Tutor generated by hbm2java
 */
public class Tutor  implements java.io.Serializable {


     private short idTutor;
     private Persona persona;
     

    public Tutor() {
    }

	
    public Tutor(short idtutor, Persona persona) {
        this.idTutor = idtutor;
        this.persona = persona;
    }
   
    public short getIdTutor() {
        return this.idTutor;
    }
    
    public void setIdTutor(short idTutor) {
        this.idTutor = idTutor;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    




}


