/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.school;

import controller.data.ControladorEstablecimiento;
import javax.swing.JOptionPane;
import view.main.FrmPrincipal;

/**
 *
 * @author tisan
 */
public class FrmEstablecimientoPrincipal extends javax.swing.JInternalFrame {

    private FrmPrincipal frmPrincipal;
    private ControladorEstablecimiento controladorEstablecimiento;
    /**
     * Creates new form FrmEstablecimientoPrincipal
     * @param frmPrincipal
     */
    public FrmEstablecimientoPrincipal(FrmPrincipal frmPrincipal) {
        initComponents();
        this.frmPrincipal=frmPrincipal;
        this.controladorEstablecimiento=new  ControladorEstablecimiento();
        controladorEstablecimiento.cargarGrilla(tblEstablecimiento);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstablecimiento = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setClosable(true);
        setTitle("ESTABLECIMIENTO");
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(null);

        tblEstablecimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Localidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEstablecimiento);
        if (tblEstablecimiento.getColumnModel().getColumnCount() > 0) {
            tblEstablecimiento.getColumnModel().getColumn(0).setResizable(false);
            tblEstablecimiento.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 452, 210);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/door13.png"))); // NOI18N
        btnSalir.setToolTipText("SALIR");
        btnSalir.setPreferredSize(new java.awt.Dimension(40, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(530, 220, 40, 35);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/add204.png"))); // NOI18N
        btnAgregar.setToolTipText("ALTA ESTABLECIMIENTO");
        btnAgregar.setPreferredSize(new java.awt.Dimension(40, 35));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(490, 30, 40, 35);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/edit26.png"))); // NOI18N
        btnModificar.setToolTipText("EDITAR");
        btnModificar.setPreferredSize(new java.awt.Dimension(40, 35));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(490, 80, 40, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
       int respuesta= JOptionPane.showConfirmDialog(this, "¿Esta seguro de Salir?","Salir",JOptionPane.YES_NO_OPTION);
        if(respuesta==JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        FrmEstablecimientoCRUD frmEstablecimientoCRUD = new FrmEstablecimientoCRUD();
        this.frmPrincipal.getDesktopPane().add(frmEstablecimientoCRUD);
        frmEstablecimientoCRUD.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(tblEstablecimiento.getSelectedRow()!=-1){
            
        }else{
            JOptionPane.showInputDialog(this, "Debe Seleccionar un establecimiento");
        }
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstablecimiento;
    // End of variables declaration//GEN-END:variables
}
