/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.netbook;

import controller.data.ControllerNetbook;
import controller.form.ControllerFormNetbook;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.constant.ListaCaracteresNoValidos;
import model.domain.Netbook;
import view.main.FrmPrincipal;

/**
 *
 * @author wally86
 */
public class FrmNetbookCRUD extends javax.swing.JInternalFrame {
    
    private ControllerFormNetbook controladorFormularioNetbook;
    private ControllerNetbook controladorNetbook;
    private FrmPrincipal frmPrincipal;
    private char tipoOperacion;
    private Netbook netbook;

    /**
     * Creates new form FrmNetbookAlta
     *
     * @param frmPrincipal
     * @param tipoOperacion
     */
    public FrmNetbookCRUD(FrmPrincipal frmPrincipal, char tipoOperacion) {
        initComponents();
        this.controladorFormularioNetbook = new ControllerFormNetbook();
        this.controladorNetbook = new ControllerNetbook();
        this.frmPrincipal = frmPrincipal;
        this.tipoOperacion = tipoOperacion;
        
        this.netbook = frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorNetbook().getNetbook();
        controladorFormularioNetbook.ocultarLabelInfo(lblInfoNumSerie);
        controladorFormularioNetbook.ocultarLabelInfo(lblInfoMarca);
        controladorFormularioNetbook.ocultarLabelInfo(lblInfoModelo);
        controladorFormularioNetbook.ocultarLabelInfo(lblInfoOfficeKey);
        controladorFormularioNetbook.ocultarLabelInfo(lblInfoWinKey);
        controladorFormularioNetbook.ocultarLabelInfo(lblInfoIdHardware);
        controladorFormularioNetbook.ocultarLabelInfo(lblInfoCodActivador);
        cargarDatos();
    }
    
    private void cargarDatos() {
        
        switch (tipoOperacion) {
            case 'a':
                break;
            case 'm':                
                txtNumSerie.setText(netbook.getIdNetbook());//frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook().getIdNetbook());
                txtNumSerie.setEnabled(false);
                txtIdHardware.setText(netbook.getIdHardware());//frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook().getIdHardware());
                txtModelo.setText(netbook.getModelo());//frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook().getModelo());
                txtMarca.setText(netbook.getMarca());//frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook().getMarca());
                txtOfficeKey.setText(netbook.getOfficeKey());//frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook().getOfficeKey());
                txtWinKey.setText(netbook.getWindowsKey());//frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorAlumno().getNetbook().getWindowsKey());
                
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumSerie = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtIdHardware = new javax.swing.JTextField();
        txtWinKey = new javax.swing.JTextField();
        txtOfficeKey = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblEstadoOfiiceKey = new javax.swing.JLabel();
        lblInfoCampos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblInfoIdHardware = new javax.swing.JLabel();
        lblEstadoWinKey = new javax.swing.JLabel();
        lblEstadoNumSerie = new javax.swing.JLabel();
        lblEstadoMarca = new javax.swing.JLabel();
        lblEstadoModelo = new javax.swing.JLabel();
        lblEstadoOfficeKey = new javax.swing.JLabel();
        lblNumSerie = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblInfoMarca = new javax.swing.JLabel();
        lblInfoWinKey = new javax.swing.JLabel();
        lblOfficeKey = new javax.swing.JLabel();
        lblInfoOfficeKey = new javax.swing.JLabel();
        lblWinKey = new javax.swing.JLabel();
        lblInfoNumSerie = new javax.swing.JLabel();
        lblInfoModelo = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblCodigoActivador = new javax.swing.JLabel();
        txtCodigoActivador = new javax.swing.JTextField();
        lblInfoCodActivador = new javax.swing.JLabel();
        lblEstadoCodActivador = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Netbook");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/laptop112.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(680, 310));
        setPreferredSize(new java.awt.Dimension(680, 310));
        getContentPane().setLayout(null);

        txtNumSerie.setMaximumSize(new java.awt.Dimension(200, 26));
        txtNumSerie.setMinimumSize(new java.awt.Dimension(200, 26));
        txtNumSerie.setPreferredSize(new java.awt.Dimension(200, 26));
        getContentPane().add(txtNumSerie);
        txtNumSerie.setBounds(120, 10, 200, 26);

        txtModelo.setMaximumSize(new java.awt.Dimension(200, 26));
        txtModelo.setMinimumSize(new java.awt.Dimension(200, 26));
        txtModelo.setPreferredSize(new java.awt.Dimension(200, 26));
        getContentPane().add(txtModelo);
        txtModelo.setBounds(430, 60, 200, 26);

        txtMarca.setMinimumSize(new java.awt.Dimension(200, 26));
        txtMarca.setPreferredSize(new java.awt.Dimension(200, 26));
        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaKeyTyped(evt);
            }
        });
        getContentPane().add(txtMarca);
        txtMarca.setBounds(120, 60, 200, 26);

        txtIdHardware.setMinimumSize(new java.awt.Dimension(200, 26));
        txtIdHardware.setPreferredSize(new java.awt.Dimension(200, 26));
        txtIdHardware.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdHardwareKeyTyped(evt);
            }
        });
        getContentPane().add(txtIdHardware);
        txtIdHardware.setBounds(430, 10, 200, 26);

        txtWinKey.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        txtWinKey.setText("Campo Opcional");
        txtWinKey.setMinimumSize(new java.awt.Dimension(200, 26));
        txtWinKey.setPreferredSize(new java.awt.Dimension(200, 26));
        txtWinKey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWinKeyFocusGained(evt);
            }
        });
        txtWinKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWinKeyKeyTyped(evt);
            }
        });
        getContentPane().add(txtWinKey);
        txtWinKey.setBounds(120, 110, 200, 26);

        txtOfficeKey.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        txtOfficeKey.setText("Campo Opcional");
        txtOfficeKey.setMinimumSize(new java.awt.Dimension(200, 26));
        txtOfficeKey.setPreferredSize(new java.awt.Dimension(200, 26));
        txtOfficeKey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOfficeKeyFocusGained(evt);
            }
        });
        txtOfficeKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOfficeKeyKeyTyped(evt);
            }
        });
        getContentPane().add(txtOfficeKey);
        txtOfficeKey.setBounds(430, 110, 200, 26);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/floppy13.png"))); // NOI18N
        btnAceptar.setText("Guardar");
        btnAceptar.setMaximumSize(new java.awt.Dimension(110, 33));
        btnAceptar.setMinimumSize(new java.awt.Dimension(110, 33));
        btnAceptar.setPreferredSize(new java.awt.Dimension(110, 33));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(160, 235, 110, 33);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/door13.png"))); // NOI18N
        btnCancelar.setText("Salir");
        btnCancelar.setMaximumSize(new java.awt.Dimension(110, 33));
        btnCancelar.setMinimumSize(new java.awt.Dimension(110, 33));
        btnCancelar.setPreferredSize(new java.awt.Dimension(110, 33));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(430, 235, 110, 33);
        getContentPane().add(lblEstadoOfiiceKey);
        lblEstadoOfiiceKey.setBounds(630, 115, 20, 20);

        lblInfoCampos.setFont(new java.awt.Font("Century Schoolbook L", 2, 10)); // NOI18N
        lblInfoCampos.setText("* Campos de datos obligatorios");
        getContentPane().add(lblInfoCampos);
        lblInfoCampos.setBounds(10, 210, 170, 10);

        jLabel1.setText("*Id Hardware");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 14));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(355, 13, 100, 20);

        lblInfoIdHardware.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoIdHardware.setForeground(new java.awt.Color(244, 7, 7));
        lblInfoIdHardware.setText("Longitud max 20 caracteres alfanumericos");
        getContentPane().add(lblInfoIdHardware);
        lblInfoIdHardware.setBounds(430, 40, 197, 14);

        lblEstadoWinKey.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoWinKey.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoWinKey.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoWinKey);
        lblEstadoWinKey.setBounds(630, 10, 20, 20);

        lblEstadoNumSerie.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoNumSerie.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoNumSerie.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoNumSerie);
        lblEstadoNumSerie.setBounds(321, 12, 20, 20);

        lblEstadoMarca.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoMarca.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoMarca.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoMarca);
        lblEstadoMarca.setBounds(321, 65, 20, 20);

        lblEstadoModelo.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoModelo.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoModelo.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoModelo);
        lblEstadoModelo.setBounds(630, 65, 20, 20);

        lblEstadoOfficeKey.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoOfficeKey.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoOfficeKey.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoOfficeKey);
        lblEstadoOfficeKey.setBounds(320, 115, 20, 20);

        lblNumSerie.setText("*Nº de Serie");
        getContentPane().add(lblNumSerie);
        lblNumSerie.setBounds(10, 13, 100, 20);

        lblMarca.setText("*Marca");
        getContentPane().add(lblMarca);
        lblMarca.setBounds(10, 60, 80, 20);

        lblInfoMarca.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoMarca.setForeground(new java.awt.Color(244, 7, 7));
        lblInfoMarca.setText("Longitud max 20 caracteres alfanumericos");
        getContentPane().add(lblInfoMarca);
        lblInfoMarca.setBounds(120, 85, 197, 14);

        lblInfoWinKey.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoWinKey.setForeground(new java.awt.Color(244, 15, 15));
        lblInfoWinKey.setText("Longitud max 25 caracteres alfanumericos");
        getContentPane().add(lblInfoWinKey);
        lblInfoWinKey.setBounds(120, 135, 197, 14);

        lblOfficeKey.setText("Office Key");
        getContentPane().add(lblOfficeKey);
        lblOfficeKey.setBounds(355, 110, 80, 20);

        lblInfoOfficeKey.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoOfficeKey.setForeground(new java.awt.Color(244, 7, 7));
        lblInfoOfficeKey.setText("Longitud max 25 caracteres alfanumericos");
        getContentPane().add(lblInfoOfficeKey);
        lblInfoOfficeKey.setBounds(430, 135, 197, 14);

        lblWinKey.setText("Windows Key");
        getContentPane().add(lblWinKey);
        lblWinKey.setBounds(10, 110, 110, 20);

        lblInfoNumSerie.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoNumSerie.setForeground(new java.awt.Color(252, 16, 16));
        lblInfoNumSerie.setText("Longitud max 15 caracteres alfanumericos");
        getContentPane().add(lblInfoNumSerie);
        lblInfoNumSerie.setBounds(120, 35, 197, 14);

        lblInfoModelo.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoModelo.setForeground(new java.awt.Color(244, 7, 7));
        lblInfoModelo.setText("Longitud max 20 caracteres alfanumericos");
        getContentPane().add(lblInfoModelo);
        lblInfoModelo.setBounds(430, 85, 197, 14);

        lblModelo.setText("*Modelo");
        getContentPane().add(lblModelo);
        lblModelo.setBounds(355, 60, 60, 20);

        lblCodigoActivador.setText("Codigo Activador");
        getContentPane().add(lblCodigoActivador);
        lblCodigoActivador.setBounds(10, 170, 90, 14);

        txtCodigoActivador.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        txtCodigoActivador.setText("Campo Opcional");
        txtCodigoActivador.setPreferredSize(new java.awt.Dimension(200, 26));
        txtCodigoActivador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoActivadorFocusGained(evt);
            }
        });
        getContentPane().add(txtCodigoActivador);
        txtCodigoActivador.setBounds(120, 165, 200, 26);

        lblInfoCodActivador.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoCodActivador.setForeground(new java.awt.Color(244, 15, 15));
        lblInfoCodActivador.setText("Longitud max 8 caracteres alfanumericos");
        getContentPane().add(lblInfoCodActivador);
        lblInfoCodActivador.setBounds(120, 190, 191, 14);

        lblEstadoCodActivador.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoCodActivador.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoCodActivador.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoCodActivador);
        lblEstadoCodActivador.setBounds(320, 170, 20, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyTyped
        // TODO add your handling code here:
        String marca = txtModelo.getText();
        for (Character c : ListaCaracteresNoValidos.LISTA) {
            if (evt.getKeyChar() == c) {
                evt.consume();
                controladorFormularioNetbook.mostrarLabelInfo(lblInfoMarca);
            } else {
                controladorFormularioNetbook.ocultarLabelInfo(lblInfoMarca);
            }
        }
        if (marca.length() >= 20) {
            evt.consume();
            controladorFormularioNetbook.mostrarLabelInfo(lblInfoMarca);
        } else {
            controladorFormularioNetbook.ocultarLabelInfo(lblInfoMarca);
        }
    }//GEN-LAST:event_txtMarcaKeyTyped

    private void txtOfficeKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOfficeKeyKeyTyped
        // TODO add your handling code here:
        String windowsKey = txtOfficeKey.getText();
        for (Character c : ListaCaracteresNoValidos.LISTA) {
            if (evt.getKeyChar() == c) {
                evt.consume();
                controladorFormularioNetbook.mostrarLabelInfo(lblInfoOfficeKey);
            } else {
                controladorFormularioNetbook.ocultarLabelInfo(lblInfoOfficeKey);
            }
        }
        if (windowsKey.length() >= 25) {
            evt.consume();
            controladorFormularioNetbook.mostrarLabelInfo(lblInfoOfficeKey);
        } else {
            controladorFormularioNetbook.ocultarLabelInfo(lblInfoOfficeKey);
        }
    }//GEN-LAST:event_txtOfficeKeyKeyTyped

    private void txtWinKeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWinKeyKeyTyped
        // TODO add your handling code here:
        String windowsKey = txtWinKey.getText();
        for (Character c : ListaCaracteresNoValidos.LISTA) {
            if (evt.getKeyChar() == c) {
                evt.consume();
                controladorFormularioNetbook.mostrarLabelInfo(lblInfoWinKey);
            } else {
                controladorFormularioNetbook.ocultarLabelInfo(lblInfoWinKey);
            }
        }
        if (windowsKey.length() >= 25) {
            evt.consume();
            controladorFormularioNetbook.mostrarLabelInfo(lblInfoWinKey);
        } else {
            controladorFormularioNetbook.ocultarLabelInfo(lblInfoWinKey);
        }
    }//GEN-LAST:event_txtWinKeyKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if (controladorFormularioNetbook.verificarCampos(this)) {
            Netbook netbookNueva;
            String windowsKey = "xxxxxxxxxxxxxxxxxxxxxxxxx".toUpperCase();
            String officeKey = "xxxxxxxxxxxxxxxxxxxxxxxxx".toUpperCase();
            String codigoActivador = "xxxxxxxx";
            String marca = txtMarca.getText().toUpperCase();
            String modelo = txtModelo.getText().toUpperCase();
            String serie = txtNumSerie.getText().toUpperCase();
            String idHardware = txtIdHardware.getText().toUpperCase();
            
            if (controladorFormularioNetbook.ingresaKeyActivador(txtWinKey.getText())) {
                windowsKey = txtWinKey.getText().toUpperCase();
            }
            if (controladorFormularioNetbook.ingresaKeyActivador(txtOfficeKey.getText())) {
                officeKey = txtOfficeKey.getText().toUpperCase();
            }
            if (controladorFormularioNetbook.ingresaKeyActivador(txtCodigoActivador.getText())) {
                codigoActivador = txtCodigoActivador.getText().toUpperCase();
            }
            switch (tipoOperacion) {
                case 'a':
                    netbookNueva = new Netbook(serie.toUpperCase(), marca.toUpperCase(), Boolean.FALSE, windowsKey.toUpperCase(), officeKey.toUpperCase(), modelo.toUpperCase(), idHardware.toUpperCase(), codigoActivador.toUpperCase());
                    if (!controladorNetbook.verificarExistencia(txtNumSerie)) {
                        controladorNetbook.agregarNetbook(netbookNueva);
                        controladorNetbook.setNetbook(netbook);
                        frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorNetbook().setNetbook(netbookNueva);
                        //actualizamos las listas
                        controladorNetbook.actualizarTblNetbookPrincipal(frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getTblNetbook(), tipoOperacion, netbookNueva);
                        try {
                            controladorNetbook.actualizarTblNetbookPrincipal(frmPrincipal.getControladorFrmPrincipal().getFrmNetbookPrincipal(frmPrincipal).getTblNetbook(), tipoOperacion, netbookNueva);
                        } catch (NullPointerException ex) {
                            
                        }
                        //actualizar anuncios
                        frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getControladorFormularioUsuario().actualizarCantidadNetbookOsciosas(frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal));
                        //mensaje de agregacion
                        JOptionPane.showMessageDialog(this, "La Netbook se agrego correctamente");
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Esta netbook ya existe en la Base De Datos");
                    }
                    break;
                case 'm':
                    netbook.setIdHardware(idHardware);
                    netbook.setMarca(marca);
                    netbook.setModelo(modelo);
                    netbook.setOfficeKey(officeKey);
                    netbook.setWindowsKey(windowsKey);
                    netbook.setCodigoActivador(codigoActivador);
                    controladorNetbook.actualizarDatosNetbook(netbook);
                    controladorNetbook.actualizarTblNetbookPrincipal(frmPrincipal.getControladorFrmPrincipal().getFrmUsuario(frmPrincipal).getTblNetbook(), tipoOperacion, netbook);
                    JOptionPane.showMessageDialog(this, "La Netbook se modifico correctamente");
                    dispose();
                    break;
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Verifique que los datos ingresados sean correctos");
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtWinKeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWinKeyFocusGained
        // TODO add your handling code here:
        txtWinKey.setText("");

    }//GEN-LAST:event_txtWinKeyFocusGained

    private void txtOfficeKeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOfficeKeyFocusGained
        // TODO add your handling code here:
        txtOfficeKey.setText("");
    }//GEN-LAST:event_txtOfficeKeyFocusGained

    private void txtIdHardwareKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdHardwareKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdHardwareKeyTyped

    private void txtCodigoActivadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoActivadorFocusGained
        // TODO add your handling code here:
        txtCodigoActivador.setText("");
    }//GEN-LAST:event_txtCodigoActivadorFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCodigoActivador;
    private javax.swing.JLabel lblEstadoCodActivador;
    private javax.swing.JLabel lblEstadoMarca;
    private javax.swing.JLabel lblEstadoModelo;
    private javax.swing.JLabel lblEstadoNumSerie;
    private javax.swing.JLabel lblEstadoOfficeKey;
    private javax.swing.JLabel lblEstadoOfiiceKey;
    private javax.swing.JLabel lblEstadoWinKey;
    private javax.swing.JLabel lblInfoCampos;
    private javax.swing.JLabel lblInfoCodActivador;
    private javax.swing.JLabel lblInfoIdHardware;
    private javax.swing.JLabel lblInfoMarca;
    private javax.swing.JLabel lblInfoModelo;
    private javax.swing.JLabel lblInfoNumSerie;
    private javax.swing.JLabel lblInfoOfficeKey;
    private javax.swing.JLabel lblInfoWinKey;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumSerie;
    private javax.swing.JLabel lblOfficeKey;
    private javax.swing.JLabel lblWinKey;
    private javax.swing.JTextField txtCodigoActivador;
    private javax.swing.JTextField txtIdHardware;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextField txtOfficeKey;
    private javax.swing.JTextField txtWinKey;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtNumeroSerie() {
        return txtNumSerie;
    }
    
    public JTextField getTxtModelo() {
        return txtModelo;
    }
    
    public JTextField getTxtMarca() {
        return txtMarca;
    }
    
    public JTextField getTxtWindowsKey() {
        return txtWinKey;
    }
    
    public JTextField getTxtOfficeKey() {
        return txtOfficeKey;
    }
    
    public JLabel getLblEstadoNumeroSerie() {
        return lblEstadoNumSerie;
    }
    
    public JLabel getLblEstadoModelo() {
        return lblEstadoModelo;
    }
    
    public JLabel getLblEstadoMarca() {
        return lblEstadoMarca;
    }
    
    public JLabel getLblEstadoWinKey() {
        return lblEstadoWinKey;
    }
    
    public JLabel getLblEstadoOfficeKey() {
        return lblEstadoOfficeKey;
    }
}
