/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;
//Controladores

import controller.data.ControllerPupil;
import controller.data.ControllerNetbook;
import controller.data.ControllerPeople;
import controller.data.ControllerUser;
import controller.data.ControladorDestino;
import controller.data.ControladorTutor;
import controller.data.ControladorServicioTecnico;
import controller.form.ControllerFormUser;
import controller.data.ControladorPase;
import controller.data.ControllerTeacher;
import controller.data.ControladorReasignacion;
import controller.data.ControllerContract;
//
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.domain.Alumno;
import model.domain.Profesor;

//Vistas
import view.pupil.FrmAlumnoCRUD;
import vista.migrar.FrmMigrarCRUD;
import view.netbook.FrmNetbookCRUD;
import view.netbook.FrmReassignrCRUD;
import vista.pase.FrmPaseCRUD;
import view.main.FrmPrincipal;
import view.teacher.FrmProfesorCRUD;
import view.technicalService.FrmServicioTecnicoCRUD;

/**
 *
 * @author wally86
 */
public class FrmUser extends javax.swing.JInternalFrame {

    private ControllerPupil controladorAlumno;
    private ControllerFormUser controladorFormularioUsuario;
    private ControllerNetbook controladorNetbook;
    private ControladorTutor controladorTutor;
    private ControllerPeople controladorPersona;
    private ControllerUser controladorUsuario;
    private ControladorReasignacion controladorReasignacion;
    private ControladorDestino controladorDestino;
    private ControladorPase controladorPase;
    private ControllerTeacher controladorProfesor;

    private ControladorServicioTecnico controladorServicioTecnico;
    private FrmPrincipal frmPrincipal;
    private int contadorNetbooksOsciosas;
    private int contadorMigracionesPendientes;
    private int contadorPasesPendientes;
    private int contadorMaquinasST;
    private int contadorReasignacion;
    private char tipoTitular;

    /**
     * Creates new form usuario
     *
     * @param frmPrincipal
     */
    public FrmUser(FrmPrincipal frmPrincipal) {
        initComponents();
        CargarGrupoRadioBoton();

        this.contadorMigracionesPendientes = 0;
        this.contadorNetbooksOsciosas = 0;
        this.contadorPasesPendientes = 0;
        this.contadorMaquinasST = 0;
        this.contadorReasignacion = 0;

        this.controladorFormularioUsuario = new ControllerFormUser();
        this.controladorAlumno = new ControllerPupil();
        this.controladorNetbook = new ControllerNetbook();
        this.controladorPersona = new ControllerPeople();
        this.controladorTutor = new ControladorTutor();
        this.controladorDestino = new ControladorDestino();
        this.controladorServicioTecnico = new ControladorServicioTecnico();
        this.controladorPase = new ControladorPase();
        this.controladorUsuario = new ControllerUser();
        this.controladorReasignacion = new ControladorReasignacion();
        this.controladorProfesor = new ControllerTeacher();

        this.controladorAlumno.cargarGrillaAlumnos(tblAlumno);
        this.controladorProfesor.cargarGrillaTitularNetbook(tblAlumno);

        this.controladorNetbook.cargaGrillaNetbook(tblNetbook, "Todas");
        this.frmPrincipal = frmPrincipal;
        this.frmPrincipal.getControladorFormulario().deshabilitarMenuItem(frmPrincipal.getMenuItemInicio());
        this.controladorFormularioUsuario.actualizarCantidadMigraciones(this);
        this.controladorFormularioUsuario.actualizarCantidadNetbookOsciosas(this);
        this.controladorFormularioUsuario.actualizarCantidadPases(this);
        this.controladorFormularioUsuario.actualizarCantidadReasignaciones(this);
        this.controladorFormularioUsuario.actualizarCantidadServicioTecnico(this);
        this.controladorUsuario.ordenarGrillaTitular(tblAlumno);
    }

    private void CargarGrupoRadioBoton() {
        ButtonGroup grupoBusqueda = new ButtonGroup();
        grupoBusqueda.add(rbtnDniAlumno);
        grupoBusqueda.add(rbtnSerieNet);
        rbtnDniAlumno.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblBuscarElemento = new javax.swing.JLabel();
        rbtnDniAlumno = new javax.swing.JRadioButton();
        rbtnSerieNet = new javax.swing.JRadioButton();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscarElemento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnMigrarAlumno = new javax.swing.JButton();
        btnVerDatosTitular = new javax.swing.JButton();
        btnModDatosAlu = new javax.swing.JButton();
        btnPase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        btnViewContract = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAgregarST = new javax.swing.JButton();
        btnReasignarNetbook = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNetbook = new javax.swing.JTable();
        btnModificarDatos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCantidadReasignaciones = new javax.swing.JLabel();
        lblCantidadPases = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCantidadMigraciones = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCantidadNetOsciosa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCantidadNetST = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setTitle("INICIO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/laptop112.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(860, 540));
        setPreferredSize(new java.awt.Dimension(860, 540));
        getContentPane().setLayout(null);

        lblBuscarElemento.setText("BUSCAR POR");
        getContentPane().add(lblBuscarElemento);
        lblBuscarElemento.setBounds(10, 33, 70, 14);

        rbtnDniAlumno.setText("DNI");
        rbtnDniAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDniAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnDniAlumno);
        rbtnDniAlumno.setBounds(80, 30, 60, 23);

        rbtnSerieNet.setText("Nº Serie");
        rbtnSerieNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSerieNetActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnSerieNet);
        rbtnSerieNet.setBounds(148, 30, 90, 23);

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(txtBusqueda);
        txtBusqueda.setBounds(250, 30, 200, 20);

        btnBuscarElemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/search102.png"))); // NOI18N
        btnBuscarElemento.setToolTipText("Buscar");
        btnBuscarElemento.setMaximumSize(new java.awt.Dimension(80, 35));
        btnBuscarElemento.setMinimumSize(new java.awt.Dimension(80, 35));
        btnBuscarElemento.setPreferredSize(new java.awt.Dimension(80, 35));
        btnBuscarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarElementoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarElemento);
        btnBuscarElemento.setBounds(475, 28, 80, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Titular de Netbook"));
        jPanel1.setLayout(null);

        btnMigrarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/migrate.png"))); // NOI18N
        btnMigrarAlumno.setToolTipText("Migrar");
        btnMigrarAlumno.setMaximumSize(new java.awt.Dimension(80, 35));
        btnMigrarAlumno.setMinimumSize(new java.awt.Dimension(80, 35));
        btnMigrarAlumno.setPreferredSize(new java.awt.Dimension(80, 35));
        btnMigrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMigrarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMigrarAlumno);
        btnMigrarAlumno.setBounds(470, 17, 90, 40);

        btnVerDatosTitular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/binoculars11.png"))); // NOI18N
        btnVerDatosTitular.setToolTipText("Ver Datos");
        btnVerDatosTitular.setMaximumSize(new java.awt.Dimension(80, 35));
        btnVerDatosTitular.setMinimumSize(new java.awt.Dimension(80, 35));
        btnVerDatosTitular.setPreferredSize(new java.awt.Dimension(80, 35));
        btnVerDatosTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatosTitularActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerDatosTitular);
        btnVerDatosTitular.setBounds(470, 61, 90, 40);

        btnModDatosAlu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/edit26.png"))); // NOI18N
        btnModDatosAlu.setToolTipText("Modificar Datos");
        btnModDatosAlu.setMaximumSize(new java.awt.Dimension(80, 35));
        btnModDatosAlu.setMinimumSize(new java.awt.Dimension(80, 35));
        btnModDatosAlu.setPreferredSize(new java.awt.Dimension(80, 35));
        btnModDatosAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModDatosAluActionPerformed(evt);
            }
        });
        jPanel1.add(btnModDatosAlu);
        btnModDatosAlu.setBounds(470, 105, 90, 40);

        btnPase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/receiveStudent.png"))); // NOI18N
        btnPase.setToolTipText("Solicitar Pase");
        btnPase.setMaximumSize(new java.awt.Dimension(80, 35));
        btnPase.setMinimumSize(new java.awt.Dimension(80, 35));
        btnPase.setPreferredSize(new java.awt.Dimension(80, 35));
        btnPase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnPase);
        btnPase.setBounds(470, 150, 90, 40);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(453, 200));

        tblAlumno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Apellido y Nombre", "Curso", "Dni"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblAlumno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblAlumnoFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumno);
        if (tblAlumno.getColumnModel().getColumnCount() > 0) {
            tblAlumno.getColumnModel().getColumn(1).setResizable(false);
            tblAlumno.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(6, 17, 453, 157);

        btnViewContract.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        btnViewContract.setText("Ver Contrato");
        btnViewContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewContractActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewContract);
        btnViewContract.setBounds(570, 17, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 670, 200);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Netbook"));
        jPanel2.setPreferredSize(new java.awt.Dimension(660, 250));
        jPanel2.setLayout(null);

        btnAgregarST.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/setting2.png"))); // NOI18N
        btnAgregarST.setToolTipText("Agregar A Servicio Tecnico");
        btnAgregarST.setMaximumSize(new java.awt.Dimension(80, 35));
        btnAgregarST.setMinimumSize(new java.awt.Dimension(80, 35));
        btnAgregarST.setPreferredSize(new java.awt.Dimension(80, 35));
        btnAgregarST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSTActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarST);
        btnAgregarST.setBounds(470, 17, 90, 40);

        btnReasignarNetbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/reassignNet.png"))); // NOI18N
        btnReasignarNetbook.setToolTipText("Reasignar");
        btnReasignarNetbook.setMaximumSize(new java.awt.Dimension(80, 35));
        btnReasignarNetbook.setMinimumSize(new java.awt.Dimension(80, 35));
        btnReasignarNetbook.setPreferredSize(new java.awt.Dimension(80, 35));
        btnReasignarNetbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReasignarNetbookActionPerformed(evt);
            }
        });
        jPanel2.add(btnReasignarNetbook);
        btnReasignarNetbook.setBounds(470, 105, 90, 40);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(453, 200));

        tblNetbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblNetbook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nº Serie", "Id Hardware", "Modelo", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNetbook.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblNetbook.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblNetbookFocusGained(evt);
            }
        });
        jScrollPane3.setViewportView(tblNetbook);
        if (tblNetbook.getColumnModel().getColumnCount() > 0) {
            tblNetbook.getColumnModel().getColumn(1).setResizable(false);
            tblNetbook.getColumnModel().getColumn(2).setResizable(false);
            tblNetbook.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(6, 17, 450, 160);

        btnModificarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/edit26.png"))); // NOI18N
        btnModificarDatos.setToolTipText("Modifica Datos");
        btnModificarDatos.setMaximumSize(new java.awt.Dimension(80, 35));
        btnModificarDatos.setMinimumSize(new java.awt.Dimension(80, 35));
        btnModificarDatos.setPreferredSize(new java.awt.Dimension(80, 35));
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificarDatos);
        btnModificarDatos.setBounds(470, 60, 90, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 270, 600, 200);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Anuncios"));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        jLabel1.setText("Pases Pendientes ");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(6, 17, 110, 30);

        lblCantidadReasignaciones.setForeground(new java.awt.Color(31, 156, 233));
        lblCantidadReasignaciones.setText("Total de : 0");
        jPanel3.add(lblCantidadReasignaciones);
        lblCantidadReasignaciones.setBounds(10, 245, 110, 14);

        lblCantidadPases.setForeground(new java.awt.Color(31, 156, 233));
        lblCantidadPases.setText("Total de : 0");
        jPanel3.add(lblCantidadPases);
        lblCantidadPases.setBounds(10, 45, 110, 14);

        jLabel3.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        jLabel3.setText("Migraciones Pendientes");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(6, 70, 114, 20);

        lblCantidadMigraciones.setForeground(new java.awt.Color(31, 156, 233));
        lblCantidadMigraciones.setText("Total de : 0");
        jPanel3.add(lblCantidadMigraciones);
        lblCantidadMigraciones.setBounds(10, 95, 110, 14);

        jLabel4.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        jLabel4.setText("Maquinas Osciosas");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(6, 120, 92, 20);

        lblCantidadNetOsciosa.setForeground(new java.awt.Color(31, 156, 233));
        lblCantidadNetOsciosa.setText("Total de : 0");
        jPanel3.add(lblCantidadNetOsciosa);
        lblCantidadNetOsciosa.setBounds(10, 145, 110, 14);

        jLabel5.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        jLabel5.setText("Reasig. Pendientes");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(6, 220, 120, 20);

        jLabel6.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        jLabel6.setText("Serv. Téc.  Pendintes");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(6, 170, 120, 20);

        lblCantidadNetST.setForeground(new java.awt.Color(31, 156, 233));
        lblCantidadNetST.setText("Total de : 0");
        jPanel3.add(lblCantidadNetST);
        lblCantidadNetST.setBounds(10, 195, 110, 14);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(685, 60, 140, 390);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/door13.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(80, 35));
        btnSalir.setMinimumSize(new java.awt.Dimension(80, 35));
        btnSalir.setPreferredSize(new java.awt.Dimension(80, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(760, 460, 80, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.getFrmPrincipal().getControladorFormulario().habilitarMenuItem(getFrmPrincipal().getMenuItemInicio());
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        // TODO add your handling code here:
        String cadena = txtBusqueda.getText();
        if (rbtnDniAlumno.isSelected()) {
            if ((!Character.isDigit(evt.getKeyChar())) && (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) && (evt.getKeyChar() != KeyEvent.VK_A)) {
                evt.consume();
                JOptionPane.showMessageDialog(this, "Caracter no permitido");
            }
            if ((cadena.length() >= 8) && (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
            }
        } else {
            if ((evt.getKeyChar() != KeyEvent.VK_A) && (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) && (!Character.isDigit(evt.getKeyChar()))) {
                evt.consume();
                JOptionPane.showMessageDialog(this, "Caracter no permitido");
            }

            if ((cadena.length() >= 15) && (evt.getKeyChar() != KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
            }

        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void rbtnSerieNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSerieNetActionPerformed
        // TODO add your handling code here:
        txtBusqueda.setText("");
    }//GEN-LAST:event_rbtnSerieNetActionPerformed

    private void rbtnDniAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDniAlumnoActionPerformed
        // TODO add your handling code here:
        txtBusqueda.setText("");
    }//GEN-LAST:event_rbtnDniAlumnoActionPerformed

    private void btnBuscarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarElementoActionPerformed
        // TODO add your handling code here:
        this.controladorUsuario.buscarTitularNetbook(this);
    }//GEN-LAST:event_btnBuscarElementoActionPerformed

    private void btnMigrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMigrarAlumnoActionPerformed
        // TODO add your handling code here:
        if (tblAlumno.getSelectedRow() != -1) {
            FrmMigrarCRUD frmMigrarPrincipal = new FrmMigrarCRUD(this, 'a');
            this.frmPrincipal.getDesktopPane().add(frmMigrarPrincipal);
            frmMigrarPrincipal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Alumno");
        }
    }//GEN-LAST:event_btnMigrarAlumnoActionPerformed

    private void btnVerDatosTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatosTitularActionPerformed
        // TODO add your handling code here:
        if (tblAlumno.getSelectedRow() != -1) {
            if (tblAlumno.getValueAt(tblAlumno.getSelectedRow(), 1).equals("DOCENTE")) {
                FrmProfesorCRUD frmProfesorCRUD = new FrmProfesorCRUD(frmPrincipal, 'v');
                frmPrincipal.getDesktopPane().add(frmProfesorCRUD);
                frmProfesorCRUD.setVisible(true);
            } else {
                FrmAlumnoCRUD frmAlumnoAlta = new FrmAlumnoCRUD(frmPrincipal, 'v');
                frmPrincipal.getDesktopPane().add(frmAlumnoAlta);
                frmAlumnoAlta.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Alumno");
        }
    }//GEN-LAST:event_btnVerDatosTitularActionPerformed

    private void btnModDatosAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModDatosAluActionPerformed
        // TODO add your handling code here:
        if (tblAlumno.getSelectedRow() != -1) {
            if (tblAlumno.getValueAt(tblAlumno.getSelectedRow(), 1).equals("DOCENTE")) {
                FrmProfesorCRUD frmProfesorCRUD = new FrmProfesorCRUD(frmPrincipal, 'm');
                frmPrincipal.getDesktopPane().add(frmProfesorCRUD);
                frmProfesorCRUD.setVisible(true);
            } else {
                FrmAlumnoCRUD frmAlumnoAlta = new FrmAlumnoCRUD(frmPrincipal, 'm');
                frmPrincipal.getDesktopPane().add(frmAlumnoAlta);
                frmAlumnoAlta.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Alumno");
        }
    }//GEN-LAST:event_btnModDatosAluActionPerformed

    private void btnAgregarSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSTActionPerformed
        // TODO add your handling code here:
        if (tblNetbook.getSelectedRow() != -1) {
            FrmServicioTecnicoCRUD frmServicioTecnicoPrincipal = new FrmServicioTecnicoCRUD(frmPrincipal, 'a', tipoTitular);
            frmPrincipal.getDesktopPane().add(frmServicioTecnicoPrincipal);
            frmServicioTecnicoPrincipal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Netbook");
        }
    }//GEN-LAST:event_btnAgregarSTActionPerformed

    private void tblAlumnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblAlumnoFocusGained
        // TODO add your handling code here:
        if (tblAlumno.getSelectedRow() != -1) {
            int dniSeleccionado = Integer.parseInt(String.valueOf(tblAlumno.getValueAt(tblAlumno.getSelectedRow(), 2)));
            if (String.valueOf(tblAlumno.getValueAt(tblAlumno.getSelectedRow(), 1)).equals("DOCENTE")) {
                getControladorProfesor().setProfesor(controladorProfesor.buscarProfesorPorDni(dniSeleccionado));
                getControladorProfesor().setNetbook(getControladorNetbook().buscarNetbookSerie(getControladorProfesor().getProfesor().getNetbook().getIdNetbook()));
                getControladorProfesor().setPersonaProfesor(getControladorPersona().buscarPersonaPorId(getControladorProfesor().getProfesor().getPersona().getIdPersona()));
                tipoTitular = 'd';
            } else {
                getControladorAlumno().setAlumno(getControladorAlumno().buscarAlumnoPorDni(dniSeleccionado));
                getControladorAlumno().setNetbook(getControladorNetbook().buscarNetbookSerie(getControladorAlumno().getAlumno().getNetbook().getIdNetbook()));
                getControladorAlumno().setPersonaAlumno(getControladorPersona().buscarPersonaPorId(getControladorAlumno().getAlumno().getPersona().getIdPersona()));
                getControladorAlumno().setTutor(getControladorTutor().buscarTutorPorId(getControladorAlumno().getAlumno().getTutor().getIdTutor()));
                getControladorAlumno().setPersonaTutor(getControladorPersona().buscarPersonaPorId(getControladorAlumno().getTutor().getPersona().getIdPersona()));
                tipoTitular = 'a';
            }
        }
    }//GEN-LAST:event_tblAlumnoFocusGained

    private void btnPaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaseActionPerformed
        // TODO add your handling code here:
        if (tblAlumno.getSelectedRow() != -1) {

            FrmPaseCRUD frmPasePrincipal = new FrmPaseCRUD(this, tipoTitular);
            frmPrincipal.getDesktopPane().add(frmPasePrincipal);
            frmPasePrincipal.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Alumno antes de continuar");
        }
    }//GEN-LAST:event_btnPaseActionPerformed

    private void tblNetbookFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblNetbookFocusGained
        // TODO add your handling code here:
        String numeroSerieSeleccionado = String.valueOf(tblNetbook.getValueAt(tblNetbook.getSelectedRow(), 0));
        try {
            getControladorAlumno().setAlumno(getControladorAlumno().buscarAlumnoPorNetbook(numeroSerieSeleccionado));
            getControladorAlumno().setNetbook(getControladorNetbook().buscarNetbookSerie(getControladorAlumno().getAlumno().getNetbook().getIdNetbook()));
            getControladorAlumno().setPersonaAlumno(getControladorPersona().buscarPersonaPorId(getControladorAlumno().getAlumno().getPersona().getIdPersona()));
            getControladorAlumno().setTutor(getControladorTutor().buscarTutorPorId(getControladorAlumno().getAlumno().getTutor().getIdTutor()));
            getControladorAlumno().setPersonaTutor(getControladorPersona().buscarPersonaPorId(getControladorAlumno().getTutor().getPersona().getIdPersona()));
            getControladorNetbook().setNetbook(getControladorAlumno().getNetbook());
            tipoTitular = 'a';
        } catch (NullPointerException ex) {
            try {
                getControladorProfesor().setProfesor(getControladorProfesor().buscarProfesorNetbook(numeroSerieSeleccionado));
            } catch (NullPointerException e) {
                getControladorProfesor().setProfesor(null);
            }
            getControladorProfesor().setNetbook(getControladorNetbook().buscarNetbookSerie(numeroSerieSeleccionado));
            try {
                getControladorProfesor().setPersonaProfesor(getControladorPersona().buscarPersonaPorId(getControladorProfesor().getProfesor().getPersona().getIdPersona()));
            } catch (NullPointerException e) {
                getControladorProfesor().setPersonaProfesor(null);
            }
            getControladorNetbook().setNetbook(getControladorProfesor().getNetbook());
            tipoTitular = 'd';
        }
    }//GEN-LAST:event_tblNetbookFocusGained

    private void btnReasignarNetbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReasignarNetbookActionPerformed
        // TODO add your handling code here:
        if (tblNetbook.getSelectedRow() != -1) {
            FrmReassignrCRUD frmReasignarPrincipal = new FrmReassignrCRUD(frmPrincipal, 'a');
            frmPrincipal.getDesktopPane().add(frmReasignarPrincipal);
            frmReasignarPrincipal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Netbook");
        }
    }//GEN-LAST:event_btnReasignarNetbookActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        // TODO add your handling code here:
        if (tblNetbook.getSelectedRow() != -1) {
            FrmNetbookCRUD frmNetbookAlta = new FrmNetbookCRUD(frmPrincipal, 'm');
            frmPrincipal.getDesktopPane().add(frmNetbookAlta);
            frmNetbookAlta.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Netbook");
        }
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnViewContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewContractActionPerformed
        // TODO add your handling code here:
        String type = "";
        if (tblAlumno.getSelectedRow() != -1) {
            if (tblAlumno.getValueAt(tblAlumno.getSelectedRow(), 1).equals("DOCENTE")) {
                type = "teacher";

            } else {
                type = "students";
            }
        }
        try {
            ControllerContract.ViewContract(type, getControladorAlumno().getAlumno(), getControladorProfesor().getProfesor());
        } catch (IOException ex) {
            Logger.getLogger(FrmUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewContractActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarST;
    private javax.swing.JButton btnBuscarElemento;
    private javax.swing.JButton btnMigrarAlumno;
    private javax.swing.JButton btnModDatosAlu;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnPase;
    private javax.swing.JButton btnReasignarNetbook;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerDatosTitular;
    private javax.swing.JButton btnViewContract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblBuscarElemento;
    private javax.swing.JLabel lblCantidadMigraciones;
    private javax.swing.JLabel lblCantidadNetOsciosa;
    private javax.swing.JLabel lblCantidadNetST;
    private javax.swing.JLabel lblCantidadPases;
    private javax.swing.JLabel lblCantidadReasignaciones;
    private javax.swing.JRadioButton rbtnDniAlumno;
    private javax.swing.JRadioButton rbtnSerieNet;
    private javax.swing.JTable tblAlumno;
    private javax.swing.JTable tblNetbook;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    public JTable getTblNetbook() {
        return tblNetbook;
    }

    public JTable getTblAlumno() {
        return tblAlumno;
    }

    /**
     * @return the controladorAlumno
     */
    public ControllerPupil getControladorAlumno() {
        return controladorAlumno;
    }

    /**
     * @return the controladorFormularioUsuario
     */
    public ControllerFormUser getControladorFormularioUsuario() {
        return controladorFormularioUsuario;
    }

    /**
     * @return the controladorNetbook
     */
    public ControllerNetbook getControladorNetbook() {
        return controladorNetbook;
    }

    /**
     * @param controladorNetbook the controladorNetbook to set
     */
    public void setControladorNetbook(ControllerNetbook controladorNetbook) {
        this.controladorNetbook = controladorNetbook;
    }

    /**
     * @return the controladorTutor
     */
    public ControladorTutor getControladorTutor() {
        return controladorTutor;
    }

    /**
     * @return the controladorPersona
     */
    public ControllerPeople getControladorPersona() {
        return controladorPersona;
    }

    public ControladorDestino getControladorDestino() {
        return this.controladorDestino;
    }

    public ControladorPase getControladorPase() {
        return this.controladorPase;
    }

    public ControladorServicioTecnico getControladorST() {
        return this.controladorServicioTecnico;
    }

    public ControllerTeacher getControladorProfesor() {
        return this.controladorProfesor;
    }

    /**
     * @return the frmPrincipal
     */
    public FrmPrincipal getFrmPrincipal() {
        return frmPrincipal;
    }

    public JRadioButton getRbtnDniAlumno() {
        return rbtnDniAlumno;
    }

    public JTextField getTxtBusqueda() {
        return txtBusqueda;
    }

    //ANUNCIO
    //LABELS
    public JLabel getLblNetbookOsciosa() {
        return lblCantidadNetOsciosa;
    }

    public JLabel getLblMigracionesPendientes() {
        return lblCantidadMigraciones;
    }

    public JLabel getLblPasesPendientes() {
        return lblCantidadPases;
    }

    public JLabel getLblMaquinasST() {
        return lblCantidadNetST;
    }

    public JLabel getLblReasignaciones() {
        return lblCantidadReasignaciones;
    }
    //GETs AND SETERs VARIABLES CONTADORES

    public int getContadorPasesPendientes() {
        return this.contadorPasesPendientes;
    }

    public void setContadorPasesPendientes(int valor) {
        this.contadorPasesPendientes = valor;
    }

    public int getContadorMigracionesPenientes() {
        return this.getContadorMigracionesPendientes();
    }

    public void setContadorMigracionesPenientes(int valor) {
        this.setContadorMigracionesPendientes(valor);
    }

    public int getContadorNetbooksOsciosas() {
        return this.contadorNetbooksOsciosas;
    }

    public void SetContadorNetbooksOsciosas(int valor) {
        this.setContadorNetbooksOsciosas(valor);
    }

    public int getContadorNetbooksST() {

        return this.getContadorMaquinasST();

    }

    public void setContadorNetbooksST(int valor) {

        this.setContadorMaquinasST(valor);

    }

    /**
     * @return the contadorMigracionesPendientes
     */
    public int getContadorMigracionesPendientes() {
        return contadorMigracionesPendientes;
    }

    /**
     * @return the contadorMaquinasST
     */
    public int getContadorMaquinasST() {
        return contadorMaquinasST;
    }

    /**
     * @return the contadorReasignacion
     */
    public int getContadorReasignacion() {
        return contadorReasignacion;
    }

    /**
     * @param contadorNetbooksOsciosas the contadorNetbooksOsciosas to set
     */
    public void setContadorNetbooksOsciosas(int contadorNetbooksOsciosas) {
        this.contadorNetbooksOsciosas = contadorNetbooksOsciosas;
    }

    /**
     * @param contadorMigracionesPendientes the contadorMigracionesPendientes to
     * set
     */
    public void setContadorMigracionesPendientes(int contadorMigracionesPendientes) {
        this.contadorMigracionesPendientes = contadorMigracionesPendientes;
    }

    /**
     * @param contadorMaquinasST the contadorMaquinasST to set
     */
    public void setContadorMaquinasST(int contadorMaquinasST) {
        this.contadorMaquinasST = contadorMaquinasST;
    }

    /**
     * @param contadorReasignacion the contadorReasignacion to set
     */
    public void setContadorReasignacion(int contadorReasignacion) {
        this.contadorReasignacion = contadorReasignacion;
    }

    /**
     * @return the controladorReasignacion
     */
    public ControladorReasignacion getControladorReasignacion() {
        return controladorReasignacion;
    }
}
