/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.pupil;

import com.mchange.io.FileUtils;
import controller.data.ControllerContract;
import controller.data.ControllerPeople;
import controller.data.ControllerPupil;
import controller.form.ControladorFrmAlumnoPrincipal;
import hibernate.dao.ContratoDAO;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URI;
import java.nio.channels.FileChannel;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.domain.Alumno;
import model.domain.ContratoAlumno;
import model.domain.Persona;
import model.report.Informe;
import org.codehaus.groovy.control.messages.Message;
import view.main.FrmPrincipal;

/**
 *
 * @author tisan
 */
public class FrmAlumnoPrincipal extends javax.swing.JInternalFrame {
    
    private final FrmPrincipal frmPrincipal;
    private final ControllerPupil controladorAlumno;
    private final ControladorFrmAlumnoPrincipal controladorFrmAlumnoPrincipal;

    /**
     * Creates new form FrmAlumnoPrincipal
     *
     * @param frmPrincipal
     */
    public FrmAlumnoPrincipal(FrmPrincipal frmPrincipal) {
        initComponents();
        this.frmPrincipal = frmPrincipal;
        this.controladorAlumno = new ControllerPupil();
        this.controladorFrmAlumnoPrincipal = new ControladorFrmAlumnoPrincipal();
        cargarDatos();
        
    }
    
    private void cargarDatos() {
        controladorAlumno.cargarGrillaAlumnos(tblAlumnos, String.valueOf(cmbVistaAlumno.getSelectedItem()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbVistaAlumno = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        btnAlumnoNuevo = new javax.swing.JButton();
        btnInfomePDF = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLoadContract = new javax.swing.JButton();

        setTitle("ADMINISTRACIÓN DE ALUMNOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/user91.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(null);

        jLabel1.setText("Mostrar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 12, 50, 14);

        cmbVistaAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Regulares", "Abandonan con Equipo", "Abandonan sin Equipo", "Egresados a Recibir", "Egresados con Equipo", "Egresados no corresponde Equipo" }));
        cmbVistaAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVistaAlumnoItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbVistaAlumno);
        cmbVistaAlumno.setBounds(70, 10, 210, 20);

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Alunmo", "Curso", "Netbook"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);
        if (tblAlumnos.getColumnModel().getColumnCount() > 0) {
            tblAlumnos.getColumnModel().getColumn(0).setResizable(false);
            tblAlumnos.getColumnModel().getColumn(1).setResizable(false);
            tblAlumnos.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 450, 150);

        btnAlumnoNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/add204.png"))); // NOI18N
        btnAlumnoNuevo.setToolTipText("Nuevo");
        btnAlumnoNuevo.setMaximumSize(new java.awt.Dimension(40, 35));
        btnAlumnoNuevo.setMinimumSize(new java.awt.Dimension(40, 35));
        btnAlumnoNuevo.setPreferredSize(new java.awt.Dimension(40, 35));
        btnAlumnoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlumnoNuevo);
        btnAlumnoNuevo.setBounds(480, 35, 50, 50);

        btnInfomePDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/file-format.png"))); // NOI18N
        btnInfomePDF.setToolTipText("Ver PDF");
        btnInfomePDF.setMaximumSize(new java.awt.Dimension(40, 35));
        btnInfomePDF.setMinimumSize(new java.awt.Dimension(40, 35));
        btnInfomePDF.setPreferredSize(new java.awt.Dimension(40, 35));
        btnInfomePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfomePDFActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfomePDF);
        btnInfomePDF.setBounds(480, 90, 50, 50);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/door13.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(40, 35));
        btnSalir.setMinimumSize(new java.awt.Dimension(40, 35));
        btnSalir.setPreferredSize(new java.awt.Dimension(40, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(510, 210, 50, 50);

        btnLoadContract.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        btnLoadContract.setText("Cargar Contrato");
        btnLoadContract.setToolTipText("CARGAR CONTRATO");
        btnLoadContract.setName(""); // NOI18N
        btnLoadContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadContractActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadContract);
        btnLoadContract.setBounds(480, 145, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnoNuevoActionPerformed
        // TODO add your handling code here:
        FrmAlumnoCRUD frmAlumnoCRUD = new FrmAlumnoCRUD(frmPrincipal, 'a');
        this.frmPrincipal.getDesktopPane().add(frmAlumnoCRUD);
        frmAlumnoCRUD.setVisible(true);
    }//GEN-LAST:event_btnAlumnoNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea salir?", "Salir", JOptionPane.OK_CANCEL_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbVistaAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVistaAlumnoItemStateChanged
        // TODO add your handling code here:
        String seleccion = String.valueOf(cmbVistaAlumno.getSelectedItem());
        controladorAlumno.cargarGrillaAlumnos(tblAlumnos, seleccion);
    }//GEN-LAST:event_cmbVistaAlumnoItemStateChanged

    private void btnInfomePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfomePDFActionPerformed
        // TODO add your handling code here:
        Informe informe = new Informe();
        try {
            informe.mostrarInforme(controladorFrmAlumnoPrincipal.tipoVistaSeleccionado(cmbVistaAlumno));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        

    }//GEN-LAST:event_btnInfomePDFActionPerformed

    private void btnLoadContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadContractActionPerformed
        // TODO add your handling code here:
        //MUST BE SELECT A STUDENT
        if (tblAlumnos.getSelectedRow() != -1) {

            //CHOOSE THE CONTRACT OF STUDENT, MUST BE A PDF FILE
            JFileChooser selection = new JFileChooser();
            //FILTER TO PDF FILE
            FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF", "pdf");
            selection.setFileFilter(filter);
            if (selection.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                String pathContact = selection.getSelectedFile().getAbsolutePath();
                ControllerContract.AddContract(String.valueOf(tblAlumnos.getValueAt(tblAlumnos.getSelectedRow(), 2)), pathContact);
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN ALUMNO PARA CARGAR EL CONTRATO");
        }
    }//GEN-LAST:event_btnLoadContractActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnoNuevo;
    private javax.swing.JButton btnInfomePDF;
    private javax.swing.JButton btnLoadContract;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbVistaAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlumnos;
    // End of variables declaration//GEN-END:variables
}
