/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.database;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.domain.ExportarBaseDatos;

/**
 *
 * @author tisan
 */
public class FrmExportBD extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmExportarBD
     */
    public FrmExportBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRuraExportacion = new javax.swing.JTextField();
        btnRuraExportacion = new javax.swing.JButton();
        btnRespaldar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setTitle("EXPORTAR BASE DE DATOS");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/data108.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 140));
        setPreferredSize(new java.awt.Dimension(400, 140));
        getContentPane().setLayout(null);

        txtRuraExportacion.setEditable(false);
        txtRuraExportacion.setMaximumSize(new java.awt.Dimension(330, 20));
        txtRuraExportacion.setMinimumSize(new java.awt.Dimension(330, 20));
        txtRuraExportacion.setPreferredSize(new java.awt.Dimension(330, 20));
        getContentPane().add(txtRuraExportacion);
        txtRuraExportacion.setBounds(10, 30, 330, 20);

        btnRuraExportacion.setText("...");
        btnRuraExportacion.setMaximumSize(new java.awt.Dimension(30, 20));
        btnRuraExportacion.setMinimumSize(new java.awt.Dimension(30, 20));
        btnRuraExportacion.setPreferredSize(new java.awt.Dimension(30, 20));
        btnRuraExportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuraExportacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnRuraExportacion);
        btnRuraExportacion.setBounds(350, 30, 30, 20);

        btnRespaldar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/data108.png"))); // NOI18N
        btnRespaldar.setToolTipText("Exportar Base de Datos");
        btnRespaldar.setMaximumSize(new java.awt.Dimension(40, 35));
        btnRespaldar.setMinimumSize(new java.awt.Dimension(40, 35));
        btnRespaldar.setPreferredSize(new java.awt.Dimension(40, 35));
        btnRespaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespaldarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRespaldar);
        btnRespaldar.setBounds(280, 65, 40, 35);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/door13.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(330, 65, 40, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRuraExportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuraExportacionActionPerformed
        // TODO add your handling code here:
        JFileChooser seleccion = new JFileChooser();
        if(seleccion.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            txtRuraExportacion.setText(seleccion.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnRuraExportacionActionPerformed

    private void btnRespaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespaldarActionPerformed
        // TODO add your handling code here:
        ExportarBaseDatos exportarBaseDatos = new ExportarBaseDatos(this);
        exportarBaseDatos.ExportarBaseDatos();
        JOptionPane.showMessageDialog(this, "Exportación realizada con exito");
        dispose();
    }//GEN-LAST:event_btnRespaldarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this,"¿Esta seguro de Salir?","Salir",JOptionPane.YES_NO_OPTION);
        if(respuesta== JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRespaldar;
    private javax.swing.JButton btnRuraExportacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField txtRuraExportacion;
    // End of variables declaration//GEN-END:variables

public JTextField getTxtRutaExportacion(){
    return txtRuraExportacion;
}
}
