/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.database;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.domain.ExportarBaseDatos;
import model.domain.ImportarBaseDatos;

/**
 *
 * @author tisan
 */
public class FrmImportBD extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmExportarBD
     */
    public FrmImportBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRuraImportacion = new javax.swing.JTextField();
        btnRuraImportacion = new javax.swing.JButton();
        btnRespaldar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setResizable(true);
        setTitle("IMPORTAR BASE DE DATOS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/programming3.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 140));
        setPreferredSize(new java.awt.Dimension(400, 140));
        getContentPane().setLayout(null);

        txtRuraImportacion.setEditable(false);
        txtRuraImportacion.setMaximumSize(new java.awt.Dimension(330, 20));
        txtRuraImportacion.setMinimumSize(new java.awt.Dimension(330, 20));
        txtRuraImportacion.setPreferredSize(new java.awt.Dimension(330, 20));
        getContentPane().add(txtRuraImportacion);
        txtRuraImportacion.setBounds(10, 30, 330, 20);

        btnRuraImportacion.setText("...");
        btnRuraImportacion.setMaximumSize(new java.awt.Dimension(30, 20));
        btnRuraImportacion.setMinimumSize(new java.awt.Dimension(30, 20));
        btnRuraImportacion.setPreferredSize(new java.awt.Dimension(30, 20));
        btnRuraImportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuraImportacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnRuraImportacion);
        btnRuraImportacion.setBounds(350, 30, 30, 20);

        btnRespaldar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/programming3.png"))); // NOI18N
        btnRespaldar.setToolTipText(" Importar Base de Datos");
        btnRespaldar.setMaximumSize(new java.awt.Dimension(40, 35));
        btnRespaldar.setMinimumSize(new java.awt.Dimension(40, 35));
        btnRespaldar.setPreferredSize(new java.awt.Dimension(40, 35));
        btnRespaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespaldarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRespaldar);
        btnRespaldar.setBounds(280, 65, 40, 35);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/door13.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(40, 35));
        btnSalir.setMinimumSize(new java.awt.Dimension(40, 35));
        btnSalir.setPreferredSize(new java.awt.Dimension(40, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(330, 65, 40, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRuraImportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuraImportacionActionPerformed
        // TODO add your handling code here:
        JFileChooser seleccion = new JFileChooser();
        if(seleccion.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            txtRuraImportacion.setText(seleccion.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnRuraImportacionActionPerformed

    private void btnRespaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespaldarActionPerformed
        // TODO add your handling code here:
        ImportarBaseDatos importarBaseDatos = new ImportarBaseDatos(this);
        importarBaseDatos.importarBaseDatos();;
    }//GEN-LAST:event_btnRespaldarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Esta seguro de Salir?","Salir",JOptionPane.YES_NO_OPTION);
        if(respuesta== JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRespaldar;
    private javax.swing.JButton btnRuraImportacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField txtRuraImportacion;
    // End of variables declaration//GEN-END:variables

public JTextField getTxtRutaImportar(){
    return txtRuraImportacion;
}
}
