/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.tutor;
import controller.form.ControladorFrmAltaTutor;
import controller.data.ControladorTutor;
import controller.form.ControllerFormGral;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.constant.ListaCaracteresNoValidos;
import view.user.FrmUser;
/**
 *
 * @author wally86
 */
public class FrmTutorCRUD extends javax.swing.JInternalFrame {

    private ControladorFrmAltaTutor controladorFrmTutorAlta;
    private ControladorTutor controladorTutor;
    private char tipoTransaccion;
    private FrmUser frmUsuario;
    private ControllerFormGral controladorFormularioGral;
    /**
     * Creates new form FrmTutorAlta
     * @param frmUsuario
     * @param tipoTransaccion
     */
    public FrmTutorCRUD(FrmUser frmUsuario, char tipoTransaccion) {
        initComponents();
        this.frmUsuario = frmUsuario;
        this.tipoTransaccion = tipoTransaccion;
        this.controladorFrmTutorAlta=new ControladorFrmAltaTutor();
        this.controladorFormularioGral = new ControllerFormGral();
        this.controladorTutor=new ControladorTutor();
        this.controladorFrmTutorAlta.ocultarLabellInformativo(lblInfoNombre);
        this.controladorFrmTutorAlta.ocultarLabellInformativo(lblInfoApellido);
        this.controladorFrmTutorAlta.ocultarLabellInformativo(lblInfoDni);
        cargarDatosParaActualizar();
    }

    
     private void cargarDatosParaActualizar() {
        if (tipoTransaccion == 'v') {
            controladorFormularioGral.deshabilitarJTextFiel(txtApellidoTutor);
            controladorFormularioGral.deshabilitarJTextFiel(txtNombreTutor);
            controladorFormularioGral.deshabilitarJTextFiel(txtDniTutor);
            controladorFrmTutorAlta.ocultarLabellInformativo(lblInfoCampos);
            txtApellidoTutor.setText(frmUsuario.getControladorAlumno().getPersonaTutor().getApellido());
            txtNombreTutor.setText(frmUsuario.getControladorAlumno().getPersonaTutor().getNombre());
            txtDniTutor.setText(String.valueOf(frmUsuario.getControladorAlumno().getPersonaTutor().getDni()));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfoDni = new javax.swing.JLabel();
        lblInfoApellido = new javax.swing.JLabel();
        lblInfoNombre = new javax.swing.JLabel();
        lblInfoCampos = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        txtDniTutor = new javax.swing.JTextField();
        txtNombreTutor = new javax.swing.JTextField();
        txtApellidoTutor = new javax.swing.JTextField();
        lblEstadoDni = new javax.swing.JLabel();
        lblEstadoNombre = new javax.swing.JLabel();
        lblEstadoApellido = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("TUTOR NUEVO");
        setFrameIcon(null);
        setMinimumSize(new java.awt.Dimension(370, 250));
        setPreferredSize(new java.awt.Dimension(370, 250));
        getContentPane().setLayout(null);

        lblInfoDni.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoDni.setForeground(new java.awt.Color(240, 15, 15));
        lblInfoDni.setText("Longitud max. 8 caracteres numericos");
        getContentPane().add(lblInfoDni);
        lblInfoDni.setBounds(110, 150, 200, 14);

        lblInfoApellido.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoApellido.setForeground(new java.awt.Color(240, 15, 15));
        lblInfoApellido.setText("Longitud max. 45 caracteres y solo letras");
        getContentPane().add(lblInfoApellido);
        lblInfoApellido.setBounds(110, 100, 200, 14);

        lblInfoNombre.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoNombre.setForeground(new java.awt.Color(240, 15, 15));
        lblInfoNombre.setText("Longitud max. 45 caracteres y solo letras");
        getContentPane().add(lblInfoNombre);
        lblInfoNombre.setBounds(110, 50, 200, 14);

        lblInfoCampos.setFont(new java.awt.Font("Cantarell", 2, 10)); // NOI18N
        lblInfoCampos.setText("* Campos obligatorios");
        getContentPane().add(lblInfoCampos);
        lblInfoCampos.setBounds(10, 160, 180, 14);

        lblNombre.setText("*Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(10, 27, 70, 14);

        lblApellido.setText("*Apellido");
        getContentPane().add(lblApellido);
        lblApellido.setBounds(10, 66, 70, 30);

        lblDni.setText("*Dni");
        getContentPane().add(lblDni);
        lblDni.setBounds(10, 125, 60, 14);

        txtDniTutor.setMinimumSize(new java.awt.Dimension(200, 26));
        txtDniTutor.setPreferredSize(new java.awt.Dimension(200, 26));
        txtDniTutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniTutorKeyTyped(evt);
            }
        });
        getContentPane().add(txtDniTutor);
        txtDniTutor.setBounds(110, 120, 200, 26);

        txtNombreTutor.setMinimumSize(new java.awt.Dimension(200, 26));
        txtNombreTutor.setPreferredSize(new java.awt.Dimension(200, 26));
        txtNombreTutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreTutorKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreTutor);
        txtNombreTutor.setBounds(110, 20, 200, 26);

        txtApellidoTutor.setMinimumSize(new java.awt.Dimension(200, 26));
        txtApellidoTutor.setPreferredSize(new java.awt.Dimension(200, 26));
        txtApellidoTutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoTutorKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidoTutor);
        txtApellidoTutor.setBounds(110, 70, 200, 26);

        lblEstadoDni.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoDni.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoDni.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoDni);
        lblEstadoDni.setBounds(320, 120, 20, 20);

        lblEstadoNombre.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoNombre.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoNombre.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoNombre);
        lblEstadoNombre.setBounds(320, 20, 20, 20);

        lblEstadoApellido.setMaximumSize(new java.awt.Dimension(20, 20));
        lblEstadoApellido.setMinimumSize(new java.awt.Dimension(20, 20));
        lblEstadoApellido.setPreferredSize(new java.awt.Dimension(20, 20));
        getContentPane().add(lblEstadoApellido);
        lblEstadoApellido.setBounds(320, 71, 20, 20);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/floppy13.png"))); // NOI18N
        btnAceptar.setText("Guardar");
        btnAceptar.setMaximumSize(new java.awt.Dimension(120, 26));
        btnAceptar.setMinimumSize(new java.awt.Dimension(120, 26));
        btnAceptar.setPreferredSize(new java.awt.Dimension(120, 26));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(30, 180, 120, 32);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/cancel19.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(120, 26));
        btnCancelar.setMinimumSize(new java.awt.Dimension(120, 26));
        btnCancelar.setPreferredSize(new java.awt.Dimension(120, 26));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(180, 180, 120, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreTutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTutorKeyTyped
        // TODO add your handling code here:
        String nombre = txtNombreTutor.getText();
        String pathImagen = "/model/image/";
        if (nombre.length() >= 45) {
            evt.consume();
        }
        if (Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            controladorFrmTutorAlta.mostrarLabellInformativo(lblInfoNombre);
        } else {
            controladorFrmTutorAlta.ocultarLabellInformativo(lblInfoNombre);
        }
        for (Character c : ListaCaracteresNoValidos.LISTA) {
            if (evt.getKeyChar() == c) {
                evt.consume();
                controladorFrmTutorAlta.mostrarLabellInformativo(lblInfoNombre);
            }
        }
        if ((nombre.length() <= 45) && (!nombre.isEmpty()) && (!Character.isDigit(evt.getKeyChar()))) {
            pathImagen += "si.png";
            controladorFrmTutorAlta.setCampoNombreValido(true);
        } else {
            controladorFrmTutorAlta.setCampoNombreValido(false);
            pathImagen += "no.png";
        }
        controladorFrmTutorAlta.agregarImagenEstadoLabel(lblEstadoNombre, pathImagen);
        controladorFrmTutorAlta.mostrarLabellInformativo(lblEstadoNombre);
    }//GEN-LAST:event_txtNombreTutorKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if(tipoTransaccion=='v'){
            dispose();
        }else{
        int respuesta= JOptionPane.showConfirmDialog(this,"Salir","¿Desea Salir?",JOptionPane.YES_NO_OPTION);
        if(respuesta==JOptionPane.YES_NO_OPTION){
        dispose();}
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtApellidoTutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoTutorKeyTyped
        // TODO add your handling code here:
        String apellido = txtApellidoTutor.getText();
        String pathImagen = "/model/image/";
        if (apellido.length() >= 45) {
            evt.consume();
        }
        if (Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            controladorFrmTutorAlta.mostrarLabellInformativo(lblInfoApellido);
            
        } else {
            controladorFrmTutorAlta.ocultarLabellInformativo(lblInfoApellido);
            
        }
        for (Character c : ListaCaracteresNoValidos.LISTA) {
            if (evt.getKeyChar() == c) {
                evt.consume();
                controladorFrmTutorAlta.mostrarLabellInformativo(lblInfoApellido);
                
            }
        }
        if ((apellido.length() <= 45) && (!apellido.isEmpty()) && (!Character.isDigit(evt.getKeyChar()))) {
            pathImagen += "si.png";
            controladorFrmTutorAlta.setCampoApellidoValido(true);
        } else {
            pathImagen += "no.png";
            controladorFrmTutorAlta.setCampoApellidoValido(false);
        }
        controladorFrmTutorAlta.agregarImagenEstadoLabel(lblEstadoApellido, pathImagen);
        controladorFrmTutorAlta.mostrarLabellInformativo(lblEstadoApellido);
    }//GEN-LAST:event_txtApellidoTutorKeyTyped

    private void txtDniTutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniTutorKeyTyped
        // TODO add your handling code here:
        String dni = txtDniTutor.getText();
        String pathImagen = "/model/image/";
        if (dni.length() >= 8) {
            evt.consume();
        }
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            controladorFrmTutorAlta.mostrarLabellInformativo(lblInfoDni);
        } else {
            controladorFrmTutorAlta.ocultarLabellInformativo(lblInfoDni);
        }
        for (Character c : ListaCaracteresNoValidos.LISTA) {
            if (evt.getKeyChar() == c) {
                evt.consume();
                controladorFrmTutorAlta.mostrarLabellInformativo(lblInfoDni);
            }
        }
        if (((dni.length() == 7)||(dni.length() == 8)) && (!dni.isEmpty()) && (Character.isDigit(evt.getKeyChar()))) {
            pathImagen += "si.png";
            controladorFrmTutorAlta.setCampoDniValido(true);
        } else {
            controladorFrmTutorAlta.setCampoDniValido(false);
            pathImagen += "no.png";
        }
        controladorFrmTutorAlta.agregarImagenEstadoLabel(lblEstadoDni, pathImagen);
        controladorFrmTutorAlta.mostrarLabellInformativo(lblEstadoDni);
    }//GEN-LAST:event_txtDniTutorKeyTyped

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(tipoTransaccion=='v'){
            dispose();
        }else{
        int respuesta = JOptionPane.showConfirmDialog(this,"¿Confirma guardar registro de tutor?","Guardar",JOptionPane.YES_NO_OPTION);
        if(respuesta==JOptionPane.YES_NO_OPTION){
            if(controladorFrmTutorAlta.validarCamposAGrabar(this)){
            controladorTutor.agregarTutor(this);
            JOptionPane.showMessageDialog(this, "Registro de tutor guardado correctamente");
            dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Verificque que los datod en los campos esten correctamente ingresados");
            }
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEstadoApellido;
    private javax.swing.JLabel lblEstadoDni;
    private javax.swing.JLabel lblEstadoNombre;
    private javax.swing.JLabel lblInfoApellido;
    private javax.swing.JLabel lblInfoCampos;
    private javax.swing.JLabel lblInfoDni;
    private javax.swing.JLabel lblInfoNombre;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtApellidoTutor;
    private javax.swing.JTextField txtDniTutor;
    private javax.swing.JTextField txtNombreTutor;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtNombre(){
    return txtNombreTutor;
    }
    public JTextField getTxtApellido(){
    return txtApellidoTutor;
    }
    public JTextField getTxtDni(){
    return txtDniTutor;
    }
    public JLabel getLblEstadoNombre(){
        return lblEstadoNombre;
    }
    public JLabel getLblEstadoApellido(){
        return lblEstadoApellido;
    }
    public JLabel getLblEstadoDni(){
        return lblEstadoDni;
    }
}
