/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.main;

import controller.form.ControllerFormGral;
import controller.form.ControladorFrmPrincipal;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import view.pupil.FrmAlumnoPrincipal;
import view.help.FrmContact;
import view.database.FrmExportBD;
import view.database.FrmImportBD;
import view.school.FrmEstablecimientoCRUD;
import view.school.FrmEstablecimientoPrincipal;
import vista.login.FrmLogin;
import view.netbook.FrmNetbookMain;
import view.teacher.FrmProfesorPrincipal;
import view.user.FrmUser;
/**
 *
 * @author wally86
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private ControllerFormGral formularioGral;
    private ControladorFrmPrincipal controladorFrmPrincipal;
    /**
     * Creates new form Principal
     */
    public FrmPrincipal() {
        initComponents();
        this.formularioGral=new ControllerFormGral();
        this.formularioGral.deshabilitarMenu(mnuRte);
        this.formularioGral.deshabilitarMenu(mnuHerramientas);
        this.formularioGral.deshabilitarMenuItem(mnuCerrarSesion);
        this.controladorFrmPrincipal = new ControladorFrmPrincipal();
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JDesktopPane();
        mnuPrincipal = new javax.swing.JMenuBar();
        mnuLogin = new javax.swing.JMenu();
        mnuIniciarSesion = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuRte = new javax.swing.JMenu();
        mnuInicio = new javax.swing.JMenuItem();
        mnuAlumno = new javax.swing.JMenu();
        mnuPrincipalAlumno = new javax.swing.JMenuItem();
        mnuEstablecimiento = new javax.swing.JMenu();
        mnuPrincipalEstablecimiento = new javax.swing.JMenuItem();
        mnuNetbook = new javax.swing.JMenu();
        mnuNetbookPrincipal = new javax.swing.JMenuItem();
        mnuProfesor = new javax.swing.JMenu();
        mnuProfesorPrincipal = new javax.swing.JMenuItem();
        mnuTutor = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuHerramientas = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuModificarDatos = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuContacto = new javax.swing.JMenuItem();
        mnuManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestor Netbook 1.0");

        mnuLogin.setText("Sistema");

        mnuIniciarSesion.setText("Iniciar Sesion");
        mnuIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIniciarSesionActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuIniciarSesion);

        mnuCerrarSesion.setText("Cerrar Sesion");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuCerrarSesion);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuSalir);

        mnuPrincipal.add(mnuLogin);

        mnuRte.setText("RTE");

        mnuInicio.setText("Inicio");
        mnuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInicioActionPerformed(evt);
            }
        });
        mnuRte.add(mnuInicio);

        mnuAlumno.setText("Alumno");

        mnuPrincipalAlumno.setText("Principal");
        mnuPrincipalAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrincipalAlumnoActionPerformed(evt);
            }
        });
        mnuAlumno.add(mnuPrincipalAlumno);

        mnuRte.add(mnuAlumno);

        mnuEstablecimiento.setText("Establecimientos");

        mnuPrincipalEstablecimiento.setText("Principal");
        mnuPrincipalEstablecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrincipalEstablecimientoActionPerformed(evt);
            }
        });
        mnuEstablecimiento.add(mnuPrincipalEstablecimiento);

        mnuRte.add(mnuEstablecimiento);

        mnuNetbook.setText("Netbook");

        mnuNetbookPrincipal.setText("Principal");
        mnuNetbookPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNetbookPrincipalActionPerformed(evt);
            }
        });
        mnuNetbook.add(mnuNetbookPrincipal);

        mnuRte.add(mnuNetbook);

        mnuProfesor.setText("Profesor");

        mnuProfesorPrincipal.setText("Principal");
        mnuProfesorPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfesorPrincipalActionPerformed(evt);
            }
        });
        mnuProfesor.add(mnuProfesorPrincipal);

        mnuRte.add(mnuProfesor);

        mnuTutor.setText("Tutor");

        jMenuItem3.setText("Principal");
        mnuTutor.add(jMenuItem3);

        mnuRte.add(mnuTutor);

        mnuPrincipal.add(mnuRte);

        mnuHerramientas.setText("Herramientas");

        jMenu1.setText("Base Datos");

        jMenuItem1.setText("Exportar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Importar");
        jMenuItem2.setEnabled(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mnuHerramientas.add(jMenu1);

        mnuModificarDatos.setText("Modificar Datos Personales");
        mnuHerramientas.add(mnuModificarDatos);

        mnuPrincipal.add(mnuHerramientas);

        mnuAyuda.setText("Ayuda");

        mnuContacto.setText("Contacto");
        mnuContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuContactoActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuContacto);

        mnuManual.setText("Manual del Sistema");
        mnuManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManualActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuManual);

        mnuPrincipal.add(mnuAyuda);

        setJMenuBar(mnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIniciarSesionActionPerformed
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin(this);
        pnlPrincipal.add(frmLogin);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_mnuIniciarSesionActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.pnlPrincipal.removeAll();
        this.pnlPrincipal.updateUI();
        this.formularioGral.deshabilitarMenu(mnuHerramientas);
        this.formularioGral.deshabilitarMenu(mnuRte);
        this.formularioGral.deshabilitarMenuItem(mnuCerrarSesion);
        this.formularioGral.habilitarMenuItem(mnuIniciarSesion);
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInicioActionPerformed
        // TODO add your handling code here:
        FrmUser frmUsuario = new FrmUser(this);
        pnlPrincipal.add(frmUsuario);
        frmUsuario.setVisible(true);
        this.formularioGral.deshabilitarMenuItem(this.mnuInicio);
    }//GEN-LAST:event_mnuInicioActionPerformed

    private void mnuProfesorPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfesorPrincipalActionPerformed
        // TODO add your handling code here:
            FrmProfesorPrincipal frmProfesorPrincipal = new FrmProfesorPrincipal(this);
            pnlPrincipal.add(frmProfesorPrincipal);
            frmProfesorPrincipal.setVisible(true);
    }//GEN-LAST:event_mnuProfesorPrincipalActionPerformed

    private void mnuNetbookPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNetbookPrincipalActionPerformed
        // TODO add your handling code here:
        FrmNetbookMain frmNetbookPrincipal = new FrmNetbookMain(this);
        pnlPrincipal.add(frmNetbookPrincipal);
        frmNetbookPrincipal.setVisible(true);
    }//GEN-LAST:event_mnuNetbookPrincipalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmExportBD frmExportarBD = new FrmExportBD();
        pnlPrincipal.add(frmExportarBD);
        frmExportarBD.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FrmImportBD frmImportarBd = new FrmImportBD();
        pnlPrincipal.add(frmImportarBd);
        frmImportarBd.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuPrincipalAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrincipalAlumnoActionPerformed
        // TODO add your handling code here:
        FrmAlumnoPrincipal frmAlumnoPrincipal = new FrmAlumnoPrincipal(this);
        pnlPrincipal.add(frmAlumnoPrincipal);
        frmAlumnoPrincipal.setVisible(true);
    }//GEN-LAST:event_mnuPrincipalAlumnoActionPerformed

    private void mnuPrincipalEstablecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrincipalEstablecimientoActionPerformed
        // TODO add your handling code here:
        FrmEstablecimientoPrincipal establecimientoPrincipal = new FrmEstablecimientoPrincipal(this);
        pnlPrincipal.add(establecimientoPrincipal);
        establecimientoPrincipal.setVisible(true);
    }//GEN-LAST:event_mnuPrincipalEstablecimientoActionPerformed

    private void mnuManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManualActionPerformed

    private void mnuContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuContactoActionPerformed
        // TODO add your handling code here:
            FrmContact contacto = new FrmContact();
            pnlPrincipal.add(contacto);
            contacto.setVisible(true);
    }//GEN-LAST:event_mnuContactoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mnuAlumno;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuContacto;
    private javax.swing.JMenu mnuEstablecimiento;
    private javax.swing.JMenu mnuHerramientas;
    private javax.swing.JMenuItem mnuIniciarSesion;
    private javax.swing.JMenuItem mnuInicio;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenuItem mnuManual;
    private javax.swing.JMenuItem mnuModificarDatos;
    private javax.swing.JMenu mnuNetbook;
    private javax.swing.JMenuItem mnuNetbookPrincipal;
    private javax.swing.JMenuBar mnuPrincipal;
    private javax.swing.JMenuItem mnuPrincipalAlumno;
    private javax.swing.JMenuItem mnuPrincipalEstablecimiento;
    private javax.swing.JMenu mnuProfesor;
    private javax.swing.JMenuItem mnuProfesorPrincipal;
    private javax.swing.JMenu mnuRte;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuTutor;
    private javax.swing.JDesktopPane pnlPrincipal;
    // End of variables declaration//GEN-END:variables
    public JDesktopPane getJDesktopPane(){
        return this.pnlPrincipal;
    }
    public JMenu getMenuRte(){
        return this.mnuRte;
    }
    public JMenu getMenuHerramientas(){
        return this.mnuHerramientas;
    }
    public ControllerFormGral getControladorFormulario(){
        return this.formularioGral;
    }
    public JMenuItem getMenuItemIniciarSesion(){
        return this.mnuIniciarSesion;
    }
    public JMenuItem getMenuItemInicio(){
        return this.mnuInicio;
    }
    public JMenuItem getMenuItemCerrarSesion(){
        return this.mnuCerrarSesion;
    }
   
    public JDesktopPane getDesktopPane(){
        return this.pnlPrincipal;
    }

    /**
     * @return the controladorFrmPrincipal
     */
    public ControladorFrmPrincipal getControladorFrmPrincipal() {
        return controladorFrmPrincipal;
    }
    
}
