/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.help;

/**
 *
 * @author tisan
 */
public class FrmContact extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDatosAplicacion
     */
    public FrmContact() {
        initComponents();
        this.txtInformacion.setEditable(false);
        this.txtInformacion.setAlignmentX(txtInformacion.CENTER_ALIGNMENT);
        this.txtInformacion.setAlignmentY(txtInformacion.CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacion = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();

        setTitle("Informacion De Contacto");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/model/image/question58.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        txtInformacion.setColumns(20);
        txtInformacion.setRows(5);
        txtInformacion.setText("            SiGeNet Version 1.0\n\nAutor: Walter Ernesto Saldía\nCorreo Electrónico: waltersaldia@gmail.com\nTeléfono: 03888-15430884");
        jScrollPane1.setViewportView(txtInformacion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 350, 180);

        btnSalir.setText("Salir");
        btnSalir.setMaximumSize(new java.awt.Dimension(100, 100));
        btnSalir.setMinimumSize(new java.awt.Dimension(100, 100));
        btnSalir.setPreferredSize(new java.awt.Dimension(100, 23));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(270, 240, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtInformacion;
    // End of variables declaration//GEN-END:variables
}
